language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jbake' ]; then cd .. && eval "mv $currentfolder generator-jbake" && cd generator-jbake; fi

